# Site settings
title: ANDY
header-img: img/home-bg.jpg
email: tauit.dnmd@gmail.com
copyright_name: Andy
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://tauitdnmd.github.io"
twitter_username: 
github_username:  
facebook_username:  
email_username:  tauit.dnmd@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
